apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oi69dqjg9-python
  janus-idp.io/tekton: oi69dqjg9-python
  backstage.io/kubernetes-id: oi69dqjg9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oi69dqjg9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
